---
latitude: 40.757187
longitude: -73.9812456
map_zoom: 17
name: The Hotel @ Times Square
email: reservations@hotelattimessquare.com
phone_number: 212-736-1600
address:
  street1: 59 W 46th St
  state: NY
  city: New York
  zip_code: '10036'
default_currency: USD
default_timezone: America/New_York
_hotel_id: NYCHTS
_portal_id: hotel-at-times-square
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  booking_url:
    type: string
  booking_link:
    type: string
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
booking_url: https://hotelattimessqaure.reztrip.com
booking_link: https://hotelattimessqaure.reztrip.com
site_url: https://www.newsteadbelmonthills.com
toll_free_phone: 866-706-7801
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.3
logo:
  name: HATSLogo
  content_type: image/jpeg
  date_added: 2019-10-15-100325
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  width: 606
  height: 187
  format: jpg
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  resource_type: image
  size: 29322
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1571148205/nlxurvpjbimhl3c8mkds.jpg"
  file_size: 
  alt: The Hotel @ Times Square Logo
phone: 212-719-2300
