---
latitude: 34.3188346
longitude: -95.7084137
map_zoom: 17
name: The Hotel @ Fifth Avenue
email: thafave@applecorehotels.com
phone_number: 212-736-1600 ext.3
address:
  street1: 17 W 32nd St
  state: NY
  city: New York
  zip_code: '10001'
default_currency: USD
default_timezone: America/New_York
_hotel_id: NYCH5
_portal_id: hotelatfifthavenue
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  booking_url:
    type: string
  booking_link:
    type: string
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
booking_url: https://hotelatfifthavenue.reztrip.com
booking_link: https://hotelatfifthavenue.reztrip.com
site_url: https://www.newsteadbelmonthills.com
toll_free_phone: 866-706-7801
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.3
logo:
  name: The-Hotel-at-Fifth-Avenue
  content_type: image/png
  date_added: 2019-07-17-110015
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1563375615/iiwv356ttkbv9kckxg7m.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1563375615/iiwv356ttkbv9kckxg7m.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1563375615/iiwv356ttkbv9kckxg7m.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1563375615/iiwv356ttkbv9kckxg7m.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1563375615/iiwv356ttkbv9kckxg7m.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1563375615/iiwv356ttkbv9kckxg7m.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1563375615/iiwv356ttkbv9kckxg7m.png"
  width: 1000
  height: 268
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1563375615/iiwv356ttkbv9kckxg7m.png"
  resource_type: image
  size: 7361
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1563375615/iiwv356ttkbv9kckxg7m.png"
  file_size:
  alt: The-Hotel-at-Fifth-Avenue
  caption: ''
  description: ''
phone: 212-736-1600 ext.3
