---
latitude: 25.79163
longitude: -80.12927
map_zoom: 17
name: The Sagamore Hotel
email: reservations@sagamorehotel.com
phone_number: 305-535-8088
alternate_phone_number: 877-242-6673
address:
  street1: 1671 Collins Ave
  state: FL
  city: Miami Beach
  zip_code: 33139
default_currency: USD
default_timezone: America/New_York
_hotel_id:
_portal_id:
booking_url: "https://be.synxis.com/?chain=12125&&hotel=6465"
booking_link: "https://be.synxis.com/"
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  booking_url:
    type: string
  booking_link:
    type: string
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
site_url: https://www.newsteadbelmonthills.com
toll_free_phone: 866-706-7801
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.3
logo:
  name: The Sagamore Hotel
  content_type: image/png
  date_added: 2019-06-06-051451
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1559812491/kgouw9eve6xwghysdpb7.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1559812491/kgouw9eve6xwghysdpb7.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1559812491/kgouw9eve6xwghysdpb7.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1559812491/kgouw9eve6xwghysdpb7.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1559812491/kgouw9eve6xwghysdpb7.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1559812491/kgouw9eve6xwghysdpb7.png"
  width: 567
  height: 186
  format: png
  url: "//res.cloudinary.com/traveltripperweb/image/upload/v1559812491/kgouw9eve6xwghysdpb7.png"
  resource_type: image
  size: 2578
  path: "//res.cloudinary.com/traveltripperweb/image/upload/v1559812491/kgouw9eve6xwghysdpb7.png"
  file_size:
  alt: The Sagamore Hotel
  caption: ''
  description: ''
