---
latitude: 25.79163
longitude: -80.12927
map_zoom: 17
name: The Sagamore Hotel
email: reservations@sagamorehotel.com
phone_number: 305-535-8088
address:
  street1: 1671 Collins Ave
  state: FL
  city: Miami Beach
  zip_code: 33139
default_currency: USD
default_timezone: America/New_York
_hotel_id: 
_portal_id: 
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  booking_url:
    type: string
  booking_link:
    type: string
  map_zoom:
    type: integer
  latitude:
    type: float
  longitude:
    type: float
alternate_phone_number: 877-242-6673
booking_url: https://be.synxis.com/?chain=12125&&hotel=6465
booking_link: https://be.synxis.com/
site_url: https://www.newsteadbelmonthills.com
toll_free_phone: 866-706-7801
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.3
logo:
  name: the-hotel-fifth-avenue-new-york-logo
  content_type: image/png
  date_added: 2019-07-11-132330
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  url: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  width: 220
  height: 70
  format: png
  url_raw: "//res.cloudinary.com/traveltripperweb/image/upload/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  resource_type: image
  size: 8402
  path: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_2500,w_2500/v1562865810/vroehtv5vn6ikyx8ogrp.png"
  file_size: 
  alt: the-hotel-fifth-avenue-new-york-logo
